PROJECT_NAME   = "mammography-stdunet-tompei-2"
LOG_DIR        = "/ediss_data/ediss2/xai-texture/src/models/xai-stdunet-tompei-ft/logs"
CHECKPOINT_DIR = "/ediss_data/ediss2/xai-texture/src/models/xai-stdunet-tompei-ft/checkpoints"
SPLIT_PATH     = "/ediss_data/ediss2/xai-texture/src/models/xai-stdunet-tompei-ft/data/split_indices.json"
DATA_ROOT = "/ediss_data/ediss2/xai-texture/data/TOMPEI"