PROJECT_NAME = "ham-kernel-week16-trial2"
LOG_DIR = "/ediss_data/ediss2/xai-texture/src/models/xai-ham-run2-kr/logs"
CHECKPOINT_DIR = "/ediss_data/ediss2/xai-texture/src/models/xai-ham-run2-kr/checkpoints"
SPLIT_PATH = "/ediss_data/ediss2/xai-texture/src/models/xai-ham-run2-kr/data/split_indices.json"
DATA_ROOT = "/ediss_data/ediss2/xai-texture/data/HAM10000"